apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: shopwise-secret-provider-class    # Update as needed, must match Deployment volumeAttributes.secretProviderClass
  namespace: shopwise           # Update as needed, must match Deployment and Service metadata.namespace
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:eu-west-3:648682442381:secret:dev-nest-secrets-rtSv9Q"    # Update as needed, must match your Secrets Manager secret ARN
          objectAlias: "dev-nest-eks-secrets"    # Update as needed
  